export enum OrderStatusEnum {
  PENDING_PAYMENT = "PENDING_PAYMENT",
  RECEIVED = "RECEIVED",
  IN_PREPARATION = "IN_PREPARATION",
  READY = "READY",
  DELIVERED = "DELIVERED",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}
