@host = http://localhost:3004
@service-prefix = status-service
# @host = http://localhost:31100

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ0xJRU5UIiwic3ViIjoiZTlmZDhhZjItZGQzYi00ZDUwLThjODMtMDIxZjhlMGQ3OTkzIiwiaWF0IjoxNzEwODYyMzcwLCJleHAiOjE3MTA5NDg3NzB9.B8KdObtHjMTapDpGZRhOBjt6f-Igwu_9_MxqMk6wmRs

###

# @name get-orders-queue
GET {{host}}/{{service-prefix}}/queue


### 


# @name update-order-status
PATCH {{host}}/{{service-prefix}}/e87987d0-552f-4562-ac84-647965c4dc85
content-type: application/json

{
  "status": "READY"
}

### 

# @name webhook
POST {{host}}/{{service-prefix}}/orders/webhook
content-type: application/json

{
  "resource": "https://api.mercadolibre.com/merchant_orders/15308297344",
  "topic": "merchant_order"
}


